spring:
#  profiles:
#    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xa_ticket?allowPublicKeyRetrieval=true&useSSL=false&charset=utf8
    username: jamie
    password: Hsbc1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: classpath:/db/changelog.xml
    enabled: true
#    database-change-log-lock-table: database_changelog_lock
#    database-change-log-table: database_changelog
    test-rollback-on-update: true
